name: myreallifeadventures
favicon: null
layout_spectrum: 0.7376491937320679
typography_spectrum: 0.9002862779889256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3200889176223427
  lightness: 0.35532563272863626
  saturation: 0.4384707014542073
  rhythmicContrast: 0.5550568560138345
purpose: []
